# Common properties
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        enable_lazy_load_no_trans: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#    static-path-pattern: /resources/**

whitepin:
  service-code: PTN0001

---
# local profile
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/whitepin
    username: whitepin
    password: whitepin12345
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        show_sql: true
        use_sql_comments: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 9090

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.github.whitepin.server.api.controller: DEBUG

---
# dev profile
spring:
  profiles: dev

server:
  port: 19090
